language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=coverage

install:
- pip install -U pip tox codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: cfhamlet
  password:
    secure: Uur/lmAobbpIU7mOEaCENlUfe0BELHQWiaGym8WZTyGZLAhOc91/n6+z5JIz8pSiCI+r0soA6NxEckn+gRwZHOynfYME+lNHPliVbsvlIKo0fLeUHFlwBLeXYamFTerf6TtXCrWNr0uR15Tk/P1kwa3nG78gxlIn52v7H7cjkponvWBaXID+Jrdu2HO9UikY8g6WHjIe03QgaQxRmuwID+NxosgQzHDMtEQ+Y2pIkh+TqEarD5FbgJ+XNReVExhwWQ6cTqCAn+Uoto7QZglSp/WebAw3mimfc7qT79kTHZKdmx/Hw+UOV/T3K+SuLIYZDfgGIZzzaa1yMvRjIxsW0AJq1B+KYOPVCQd6q2bPvXjbZJVMMzx75CgsyFaYNADrbLeljeEkBECafi8do8vWRfe+UrOf9WtFFwi43m71MYHhVSCLppucWVZbyQADwJ4ocAi9qAV9k3knAjd60ypbb5bgOYKRRDlh87FEzzOtVNZVfx4Pipp0lYzrlnRGcInlFAE+pltK9TV0RtEsaLYTg9zF1bomct5ZUkeVb3FojvJVKJmqm146seucZ1jyrGgdDXD8Ns9rpgEpMFoTMfLXUnZ9L4ffWcbZ4Q4vPAp1xM+rs0ybI59hQeIYy7comc7qyujxwbUA5Yneqg8N8ctiV737kOtCtbl/0nSljKoggH4=
  on:
    tags: true
    condition: ${TOXENV} == py27
